project:
  type: website
website:
  title: "ReCoDE Project"
  navbar:
    pinned: true
    background: "#3e5172"
    tools:
      - icon: twitter
        href: https://twitter.com/quintero_val
    left:
      - href: introduction.qmd
        text: Introduction
      - href: data_curation.qmd
        text: Data curation
      - href: survival_analysis.qmd
        text: Survival Analysis
      - href: extension.qmd
        text: Advanced Survival Analysis
      
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: visual